#pragma once

#include <cpp_pipelines/seq/access.hpp>
#include <cpp_pipelines/seq/accumulate.hpp>
#include <cpp_pipelines/seq/adjacent.hpp>
#include <cpp_pipelines/seq/adjacent_transform.hpp>
#include <cpp_pipelines/seq/cache_latest.hpp>
#include <cpp_pipelines/seq/checks.hpp>
#include <cpp_pipelines/seq/chunk.hpp>
#include <cpp_pipelines/seq/concat.hpp>
#include <cpp_pipelines/seq/copy.hpp>
#include <cpp_pipelines/seq/distance.hpp>
#include <cpp_pipelines/seq/drop.hpp>
#include <cpp_pipelines/seq/drop_last.hpp>
#include <cpp_pipelines/seq/drop_while.hpp>
#include <cpp_pipelines/seq/empty.hpp>
#include <cpp_pipelines/seq/enumerate.hpp>
#include <cpp_pipelines/seq/filter.hpp>
#include <cpp_pipelines/seq/for_each.hpp>
#include <cpp_pipelines/seq/generate.hpp>
#include <cpp_pipelines/seq/getlines.hpp>
#include <cpp_pipelines/seq/inspect.hpp>
#include <cpp_pipelines/seq/intersperse.hpp>
#include <cpp_pipelines/seq/iota.hpp>
#include <cpp_pipelines/seq/istream.hpp>
#include <cpp_pipelines/seq/iterate.hpp>
#include <cpp_pipelines/seq/join.hpp>
#include <cpp_pipelines/seq/order_by.hpp>
#include <cpp_pipelines/seq/repeat.hpp>
#include <cpp_pipelines/seq/reverse.hpp>
#include <cpp_pipelines/seq/split.hpp>
#include <cpp_pipelines/seq/stride.hpp>
#include <cpp_pipelines/seq/take.hpp>
#include <cpp_pipelines/seq/take_last.hpp>
#include <cpp_pipelines/seq/take_while.hpp>
#include <cpp_pipelines/seq/to.hpp>
#include <cpp_pipelines/seq/to_map.hpp>
#include <cpp_pipelines/seq/transform.hpp>
#include <cpp_pipelines/seq/transform_join.hpp>
#include <cpp_pipelines/seq/transform_maybe.hpp>
#include <cpp_pipelines/seq/transform_zip.hpp>
#include <cpp_pipelines/seq/trim_while.hpp>
#include <cpp_pipelines/seq/unfold.hpp>
#include <cpp_pipelines/seq/unique.hpp>
#include <cpp_pipelines/seq/views.hpp>
#include <cpp_pipelines/seq/write.hpp>
#include <cpp_pipelines/seq/zip.hpp>
#include <cpp_pipelines/subrange.hpp>